### PR TITLE
Added basic C/C++ support

### PR DESCRIPTION
**Pull request by Jesus89**
Just basic class, struct, enum, and functions support. Required in #8.

### CODE REVIEW

**Comment by r-chris** [comment]
Looks promising - how well does it work ?

**Comment by Jesus89** [comment]
My tests were all OK.

If you detect any missing expression, please let me know and I will add it.

**Comment by r-chris** [comment]
This repo had no activity since August 2016. I think it might be time to fork and merge those PR unless the repo owner could open access for you to merge - maybe worth trying to contact them?

**Comment by r-chris** [comment]
Thanks

**Pull request merged**
